name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   steps:
     - name: Simple JS Action
       id: greet
       # Use an actions from a repository
       uses: actions/hello-world-javascript-action@v1
       with: 
        who-to-greet: John
     - name: Log Greeting Time
       # Here references to id step and his outputs
       run: echo "${{ steps.greet.outputs.time }}"