name: Actions Workflow

on:
  push:
    # To ignore branches
    # branches-ignore:
      # - ""

    branches:
      - 'feature/*' # matches feature/featA, feature/featB
      - 'feature/*' # matches feature/featA/a
      - '!feature/featC' # To ignore one branch on feature
    
    paths:
      - "**.js" # Only run when .js file is updated or pushed
    
    # paths-ignore:
    #   - ".csv"

  pull_request:
    branches:
      - main

  # To call workflow manual external
  # repository_dispatch:
  #   types: [build]

  # To schedule workflow
  # schedule:
  #   - cron: '0/5 * * * *'
  #   - cron: '0/6 * * * *'
  
  # To call on pull request
  # pull_request:
  #   types:
  #     - closed
  #     - assigned
  #     - opened
  #     - reopened

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   steps:
     - name: payload from manual triggered
       run: echo ${{ github.event.client_payload.env }}
     - name: List Files
       run: |
         pwd
         ls -a
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         echo "${{ github.token}}"
       # Clone the actual repository in git virtual machine
     - name: Checkout
       uses: actions/checkout@v1
     - name: List Files After Checkout
       run: |
          pwd
          ls -a
     - name: Simple JS Action
       id: greet
       # Use an actions from a repository
       uses: actions/hello-world-javascript-action@v1
       with: 
        who-to-greet: John
     - name: Log Greeting Time
       # Here references to id step and his outputs
       run: echo "${{ steps.greet.outputs.time }}"