# Name of entire workflow
name: Shell commands

# Accions to trigger events
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          from datetime import datetime
          print(datetime.now())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    # Job dependency
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
    
  